---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.registry_file: /var/log/containers/filebeat_registry

    filebeat.prospectors:
    - type: log
      paths:
        - "/var/log/containers/*.log"
      exclude_files: ['filebeat*.log','kube*.log']
      symlinks: true
      json.message_key: log
      json.keys_under_root: true
      json.add_error_key: true
      multiline.pattern: '^\s'
      multiline.match: after
      document_type: kube-logs

    output.kafka:
      enabled: true
      hosts: ["kafka-kafka:9092"]
      topic: eco_logs
      compression: gzip
      max_message_bytes: 1000000
      logging.level: debug
      logging.selectors: ["*"]
      logging.to_syslog: false
      logging.metrics.enabled: true
      logging.metrics.period: 30s
      logging.to_files: true
