apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |-
    input {
      kafka {
        bootstrap_servers => "kafka-kafka:9092"
        topics_pattern    => ["logs-*"]
      }
    }
    
    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        user => "elastic"
        password => "changeme"
        index => "%{[@metadata][kafka][topic]}"
      }
    }
