apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-shipper-config
data:
  logstash-shipper.conf: |-
    input {
      beats {
        port => 5000
      }
    }

    filter {
      mutate {
        rename => ["log", "message"]
      }

      date {
        match => ["time", "ISO8601"]
        remove_field => ["time"]
      }

      grok {
        match => { "source" => "/var/log/containers/%{DATA:pod_name}_%{DATA:namespace}_%{GREEDYDATA:container_name}-%{DATA:container_id}.log" }
        remove_field => ["source"]
      }
    }

    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        user => "elastic"
        password => "changeme"
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
      }
    }
